version: '3'
services:
  dev:
    image: kyithinnu:lab1_CarPricePrediction
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./source_code:/root/sourceCode
      - ./.vscode-server:/root/.vscode-server
    