version: '3'
services:
  dev:
    image: lab1:latest
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./source_code:/root/sourceCode
      - ./vscode-sever:/root/.vscode-server
    